"""
analyst/visualization_engine.py
---------------------------------
Production visualization engine for DIPEX.

Responsibilities:
  - Select the correct chart type based on column types and cardinality
  - Generate structured JSON chart specs for the dashboard renderer
  - Detect misleading visualizations (truncated axis, cherry-picked ranges)
  - Color-blind-safe palettes + auto label/title generation
  - Only reference Gold artefact data — never Bronze/Silver
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger("dipex.visualization")

# ══════════════════════════════════════════════════════════════════════════════
# Color Palettes (WCAG 2.1 color-blind-safe)
# ══════════════════════════════════════════════════════════════════════════════

PALETTE_COLORBLIND_SAFE = [
    "#0072B2",  # blue
    "#E69F00",  # orange
    "#009E73",  # green
    "#CC79A7",  # magenta
    "#56B4E9",  # sky blue
    "#F0E442",  # yellow
    "#D55E00",  # vermillion
    "#000000",  # black
]

CONFIDENCE_COLORS = {
    "verified": "#10b981",
    "retry": "#f59e0b",
    "rejected": "#ef4444",
}

# ══════════════════════════════════════════════════════════════════════════════
# Chart Type Selection Logic
# ══════════════════════════════════════════════════════════════════════════════

def select_chart_type(
    df: pd.DataFrame,
    x_col: str,
    y_col: Optional[str] = None,
    *,
    max_cat_cardinality: int = 20,
) -> str:
    """
    Select the optimal chart type based on column types and cardinality.

    Returns one of: "bar", "line", "scatter", "heatmap", "box", "violin",
                    "histogram", "pie", "area"

    Rules (in priority order):
    1. Time x-axis → line or area
    2. Categorical x, numeric y, cardinality ≤ 20 → bar
    3. Categorical x, cardinality > 20 → box
    4. Numeric x, numeric y, row count ≤ 10K → scatter
    5. Numeric x, numeric y, row count > 10K → heatmap (2D-binned)
    6. Single numeric column → histogram
    7. Categorical with proportion analysis → pie (only if ≤ 6 categories)
    """
    if x_col not in df.columns:
        return "bar"

    x_dtype = df[x_col].dtype
    x_is_time = pd.api.types.is_datetime64_any_dtype(x_dtype)
    x_is_cat = pd.api.types.is_object_dtype(x_dtype) or pd.api.types.is_categorical_dtype(x_dtype)
    x_is_num = pd.api.types.is_numeric_dtype(x_dtype)
    x_card = int(df[x_col].nunique())

    y_is_num = (
        y_col is not None
        and y_col in df.columns
        and pd.api.types.is_numeric_dtype(df[y_col].dtype)
    )
    n_rows = len(df)

    # Priority rule application
    if x_is_time and y_is_num:
        return "line"
    if x_is_time:
        return "area"
    if x_is_cat and y_is_num and x_card <= max_cat_cardinality:
        return "bar"
    if x_is_cat and y_is_num and x_card > max_cat_cardinality:
        return "box"
    if x_is_num and y_is_num and n_rows <= 10_000:
        return "scatter"
    if x_is_num and y_is_num and n_rows > 10_000:
        return "heatmap"
    if x_is_num and y_col is None:
        return "histogram"
    if x_is_cat and y_col is None and x_card <= 6:
        return "pie"
    return "bar"


# ══════════════════════════════════════════════════════════════════════════════
# Misleading Visualization Detector
# ══════════════════════════════════════════════════════════════════════════════

class VisualizationMisleadingDetector:
    """
    Checks a chart spec for common misleading visualization patterns:
    - Truncated y-axis (non-zero baseline on bar charts)
    - Dual-axis exploitation
    - Cherry-picked date ranges
    - Inappropriate chart type for data distribution
    - Missing axis labels / units
    - Missing confidence badge on verified-data charts
    """

    def detect(self, spec: Dict[str, Any]) -> List[Dict[str, str]]:
        """
        Args:
            spec: Chart specification dict (as generated by generate_chart_config)

        Returns:
            List of {severity, flag, message} dicts. Empty = no issues.
        """
        flags = []

        chart_type = spec.get("chart_type", "")
        y_axis = spec.get("y_axis", {})
        x_axis = spec.get("x_axis", {})
        data = spec.get("data_summary", {})

        # 1. Truncated y-axis on bar chart
        if chart_type == "bar":
            y_min = y_axis.get("min")
            if y_min is not None and float(y_min) > 0:
                flags.append({
                    "severity": "WARNING",
                    "flag": "TRUNCATED_Y_AXIS",
                    "message": (
                        f"Bar chart y-axis starts at {y_min} instead of 0. "
                        "This exaggerates differences. Use y_min=0 for bars."
                    ),
                })

        # 2. Cherry-picked date range
        if chart_type in ("line", "area"):
            start = x_axis.get("start_date")
            end = x_axis.get("end_date")
            data_start = data.get("actual_start_date")
            data_end = data.get("actual_end_date")
            if start and data_start and str(start) > str(data_start):
                flags.append({
                    "severity": "WARNING",
                    "flag": "CHERRY_PICKED_DATE_START",
                    "message": (
                        f"Chart starts at {start} but data begins at {data_start}. "
                        "Possible cherry-picked date range."
                    ),
                })
            if end and data_end and str(end) < str(data_end):
                flags.append({
                    "severity": "WARNING",
                    "flag": "CHERRY_PICKED_DATE_END",
                    "message": (
                        f"Chart ends at {end} but data continues until {data_end}. "
                        "Possible cherry-picked date range."
                    ),
                })

        # 3. Missing labels
        if not x_axis.get("label"):
            flags.append({
                "severity": "INFO",
                "flag": "MISSING_X_LABEL",
                "message": "X-axis has no label. Add axis label for clarity.",
            })
        if not y_axis.get("label"):
            flags.append({
                "severity": "INFO",
                "flag": "MISSING_Y_LABEL",
                "message": "Y-axis has no label. Add axis label for clarity.",
            })

        # 4. Missing confidence badge
        if not spec.get("confidence_badge"):
            flags.append({
                "severity": "INFO",
                "flag": "MISSING_CONFIDENCE_BADGE",
                "message": "No confidence badge on chart. Add QA status and confidence score.",
            })

        # 5. Pie chart with too many slices
        if chart_type == "pie":
            n_cats = spec.get("data_summary", {}).get("n_categories", 0)
            if n_cats > 6:
                flags.append({
                    "severity": "WARNING",
                    "flag": "PIE_TOO_MANY_SLICES",
                    "message": (
                        f"Pie chart has {n_cats} categories. > 6 slices are hard to read. "
                        "Use bar or treemap instead."
                    ),
                })

        return flags


# ══════════════════════════════════════════════════════════════════════════════
# VisualizationEngine — Main Public Class
# ══════════════════════════════════════════════════════════════════════════════

class VisualizationEngine:
    """
    Main visualization engine. Generates chart specs from Gold artefacts.
    All charts reference Gold artefact data only.
    """

    def __init__(self) -> None:
        self._detector = VisualizationMisleadingDetector()

    def generate_chart_config(
        self,
        df: pd.DataFrame,
        x_col: str,
        y_col: Optional[str] = None,
        *,
        title: Optional[str] = None,
        chart_type: Optional[str] = None,
        confidence_score: Optional[float] = None,
        qa_passed: bool = True,
        gold_artefact_id: Optional[str] = None,
        operation: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Generate a JSON chart specification from a Gold artefact DataFrame.

        Args:
            df: Gold artefact DataFrame (never Bronze/Silver)
            x_col: Column for x-axis
            y_col: Column for y-axis (optional for histograms)
            title: Chart title (auto-generated if None)
            chart_type: Override chart type (auto-selected if None)
            confidence_score: Confidence score to embed in badge
            qa_passed: Whether QA passed for this artefact
            gold_artefact_id: ID of the Gold artefact this chart references
            operation: Analyst operation that produced the artefact

        Returns:
            Structured chart spec dict for dashboard renderer
        """
        # Enforce Gold-only policy
        if gold_artefact_id is None:
            logger.warning(
                "VisualizationEngine: gold_artefact_id not provided — "
                "chart may reference unverified data"
            )

        # Auto-select chart type
        resolved_chart_type = chart_type or select_chart_type(df, x_col, y_col)

        # Auto-generate title
        auto_title = title or self._auto_title(x_col, y_col, operation, resolved_chart_type)

        # Build data payload
        data_payload = self._build_data_payload(df, x_col, y_col, resolved_chart_type)

        # Build axis metadata
        x_axis_meta = self._build_axis_meta(df, x_col, "x")
        y_axis_meta = self._build_axis_meta(df, y_col, "y") if y_col else {}

        # Confidence badge
        badge = None
        if confidence_score is not None:
            badge_color = (
                CONFIDENCE_COLORS["verified"] if qa_passed and confidence_score >= 0.70
                else CONFIDENCE_COLORS["retry"] if confidence_score >= 0.50
                else CONFIDENCE_COLORS["rejected"]
            )
            badge = {
                "score": round(confidence_score, 3),
                "qa_passed": qa_passed,
                "color": badge_color,
                "label": f"Confidence: {confidence_score:.1%}",
            }

        spec = {
            "chart_type": resolved_chart_type,
            "title": auto_title,
            "x_axis": x_axis_meta,
            "y_axis": y_axis_meta,
            "data": data_payload,
            "palette": PALETTE_COLORBLIND_SAFE[:8],
            "confidence_badge": badge,
            "gold_artefact_id": gold_artefact_id,
            "operation": operation,
            "data_summary": {
                "n_rows": len(df),
                "n_categories": int(df[x_col].nunique()) if x_col in df.columns else 0,
            },
        }

        # Run misleading detector
        flags = self._detector.detect(spec)
        if flags:
            spec["misleading_flags"] = flags
            for flag in flags:
                if flag["severity"] == "WARNING":
                    logger.warning(
                        "VisualizationEngine: misleading flag [%s] %s",
                        flag["flag"], flag["message"],
                    )

        return spec

    def detect_misleading(self, spec: Dict[str, Any]) -> List[Dict[str, str]]:
        """Run the misleading detector on an existing chart spec."""
        return self._detector.detect(spec)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _auto_title(
        x_col: str,
        y_col: Optional[str],
        operation: Optional[str],
        chart_type: str,
    ) -> str:
        base = f"{chart_type.capitalize()} Chart"
        if y_col:
            base = f"{y_col.replace('_', ' ').title()} by {x_col.replace('_', ' ').title()}"
        elif operation:
            base = f"{operation.replace('_', ' ').title()}: {x_col.replace('_', ' ').title()}"
        return base

    @staticmethod
    def _build_axis_meta(df: pd.DataFrame, col: Optional[str], axis: str) -> Dict[str, Any]:
        if col is None or col not in df.columns:
            return {"label": None, "type": "unknown", "min": None, "max": None}

        series = df[col]
        dtype = series.dtype

        if pd.api.types.is_numeric_dtype(dtype):
            return {
                "label": col.replace("_", " ").title(),
                "type": "numeric",
                "min": float(series.min()),
                "max": float(series.max()),
                "unit": None,
            }
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            return {
                "label": col.replace("_", " ").title(),
                "type": "datetime",
                "start_date": str(series.min()),
                "end_date": str(series.max()),
            }
        else:
            return {
                "label": col.replace("_", " ").title(),
                "type": "categorical",
                "categories": series.dropna().unique().tolist()[:50],
            }

    @staticmethod
    def _build_data_payload(
        df: pd.DataFrame,
        x_col: str,
        y_col: Optional[str],
        chart_type: str,
        max_points: int = 1000,
    ) -> List[Dict[str, Any]]:
        """Build a compact, serializable data payload for the chart."""
        if x_col not in df.columns:
            return []

        try:
            if chart_type == "histogram":
                counts, edges = np.histogram(df[x_col].dropna(), bins=30)
                return [
                    {"bin_start": float(edges[i]), "bin_end": float(edges[i + 1]),
                     "count": int(counts[i])}
                    for i in range(len(counts))
                ]

            if chart_type in ("bar", "pie"):
                if y_col and y_col in df.columns:
                    grouped = df.groupby(x_col, observed=True)[y_col].mean().reset_index()
                else:
                    grouped = df[x_col].value_counts().reset_index()
                    grouped.columns = [x_col, "count"]
                    y_col = "count"
                return grouped.head(50).to_dict(orient="records")

            # Downsample for scatter/line/area
            sample = df[[x_col, y_col]].dropna() if y_col else df[[x_col]].dropna()
            if len(sample) > max_points:
                sample = sample.sample(max_points, random_state=42)
            return sample.to_dict(orient="records")

        except Exception as exc:  # noqa: BLE001
            logger.warning("VisualizationEngine: data payload build failed: %s", exc)
            return []
