"""
profiling/rl_profiling_strategy.py
------------------------------------
Production-grade RL Contextual Bandit for smart column profiling decisions.

Purpose
-------
Profiling large DataFrames (Shapiro-Wilk, skewness, kurtosis) is expensive.
This bandit learns which columns genuinely benefit from deep profiling vs.
which are stable/uninformative — and skips expensive stats for the latter.

Architecture
------------
State   : "{dataset_id}::{column}"
Actions : "full"  — run all stats (Shapiro, skew, kurt, outlier dual-method)
          "basic" — run only: null rate, unique count, min, max, mean, std
Reward  : flags_raised * 15  - compute_time_ms * 0.05
          (negative reward if basic profile missed a flag that full would catch)

Persistence: data/rl_profiling_strategy.json
"""

from __future__ import annotations

import json
import logging
import os
import random
from typing import Dict, List, Optional

logger = logging.getLogger("dipex.profiling.rl_strategy")

_DEFAULT_STATE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "data", "rl_profiling_strategy.json"
)
_ACTIONS:    List[str] = ["full", "basic"]
_ALPHA:      float     = 0.12
_EPSILON:    float     = 0.15
_SAVE_PROB:  float     = 0.10


class RLProfilingStrategy:
    """
    Contextual bandit that decides whether to run full or basic profiling
    per (dataset, column) pair, optimising the flags-per-compute-ms ratio.
    """

    def __init__(self, state_path: str = _DEFAULT_STATE_PATH) -> None:
        self.state_path = state_path
        self.q: Dict[str, Dict[str, float]] = {}
        self._load()

    def _load(self) -> None:
        if os.path.exists(self.state_path):
            try:
                with open(self.state_path, "r", encoding="utf-8") as fh:
                    self.q = json.load(fh)
                logger.info("RLProfilingStrategy: loaded %d states.", len(self.q))
            except Exception as exc:  # noqa: BLE001
                logger.warning("RLProfilingStrategy: Q-table load failed: %s", exc)

    def save(self) -> None:
        os.makedirs(os.path.dirname(self.state_path) or ".", exist_ok=True)
        try:
            with open(self.state_path, "w", encoding="utf-8") as fh:
                json.dump(self.q, fh, indent=2)
        except Exception as exc:  # noqa: BLE001
            logger.warning("RLProfilingStrategy: Save failed: %s", exc)

    def _state_key(self, dataset_id: str, column: str) -> str:
        return f"{dataset_id}::{column}"

    def _init_state(self, state: str) -> None:
        if state not in self.q:
            # New column: slightly favour full profile initially
            self.q[state] = {"full": 0.2, "basic": 0.0}

    def _update(self, state: str, action: str, reward: float) -> None:
        self._init_state(state)
        curr = self.q[state].get(action, 0.0)
        self.q[state][action] = round(curr + _ALPHA * (reward - curr), 6)
        if random.random() < _SAVE_PROB:
            self.save()

    # ── Public API ────────────────────────────────────────────────────────────

    def get_action(self, dataset_id: str, column: str) -> str:
        """
        Return 'full' or 'basic' profiling action for this column.

        New columns always start with a full profile to gather baseline
        statistics before the bandit has enough experience to decide.
        """
        state = self._state_key(dataset_id, column)
        self._init_state(state)

        if random.random() < _EPSILON:
            return random.choice(_ACTIONS)
        return max(self.q[state], key=self.q[state].__getitem__)

    def record_outcome(
        self,
        dataset_id:     str,
        column:         str,
        action:         str,
        flags_raised:   int,
        compute_ms:     float,
        missed_flags:   int = 0,
    ) -> None:
        """
        Update Q-table with profiling outcome.

        Parameters
        ----------
        flags_raised  : Number of analyst flags generated by this column
        compute_ms    : Wall-clock time for profiling this column (ms)
        missed_flags  : Estimated flags that would have been raised had full
                        profiling been used (only meaningful when action='basic')
        """
        state = self._state_key(dataset_id, column)
        reward = (flags_raised * 15.0) - (compute_ms * 0.05) - (missed_flags * 20.0)
        self._update(state, action, reward)
        logger.debug(
            "[RL] Profile %s::%s | action=%s | flags=%d | ms=%.1f | reward=%.2f",
            dataset_id, column, action, flags_raised, compute_ms, reward,
        )

    def get_policy_summary(self) -> Dict[str, str]:
        """Return the current learned policy as {state: best_action}."""
        return {
            s: max(v, key=v.__getitem__)
            for s, v in self.q.items() if v
        }


# ── Module-level singleton ────────────────────────────────────────────────────

_STRATEGY: Optional[RLProfilingStrategy] = None


def get_rl_strategy(state_path: str = _DEFAULT_STATE_PATH) -> RLProfilingStrategy:
    """Return the module-level singleton RLProfilingStrategy."""
    global _STRATEGY  # noqa: PLW0603
    if _STRATEGY is None:
        _STRATEGY = RLProfilingStrategy(state_path=state_path)
    return _STRATEGY
